// ignore: camel_case_types
class countries {
  int id;
  String Title;
  String flag;
  int square;
  int population;
  countries(this.id, this.flag, this.Title, this.square, this.population);
}

List<countries> countriesList = [
  countries(
      1,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/128px-Flag_of_Algeria.svg.png',
      'Алжир',
      2381740,
      39666519),
  countries(
      2,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_the_Federal_Republic_of_Southern_Cameroons.svg/128px-Flag_of_the_Federal_Republic_of_Southern_Cameroons.svg.png',
      'Амбазония',
      42710,
      3521898),
  countries(
      3,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/128px-Flag_of_Angola.svg.png',
      'Ангола',
      1246700,
      25021974),
  countries(
      4,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/128px-Flag_of_Benin.svg.png',
      'Бенин',
      112622,
      10315244),
  countries(
      5,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/128px-Flag_of_Botswana.svg.png',
      'Ботсвана',
      581726,
      2262485),
  countries(
      6,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/128px-Flag_of_Burkina_Faso.svg.png',
      'Буркина-Фасо',
      274000,
      18450494),
  countries(
      7,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/128px-Flag_of_Burundi.svg.png',
      'Бурунди',
      27830,
      11178921),
  countries(
      8,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/128px-Flag_of_Gabon.svg.png',
      'Габон',
      267668,
      1725292),
  countries(
      9,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/128px-Flag_of_The_Gambia.svg.png',
      'Гамбия',
      10380,
      1990924),
  countries(
      10,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/128px-Flag_of_Ghana.svg.png',
      'Гана',
      238534,
      27409893),
  countries(
      11,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/128px-Flag_of_Guinea.svg.png',
      'Гвинея',
      245857,
      12608590),
  countries(
      12,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/128px-Flag_of_Guinea-Bissau.svg.png',
      'Гвинея-Бисау',
      36125,
      1844325),
  countries(
      13,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/128px-Flag_of_Djibouti.svg.png',
      'Джибути',
      23200,
      887861),
  countries(
      14,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/128px-Flag_of_Egypt.svg.png',
      'Египет',
      1001449,
      87266562),
  countries(
      15,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/128px-Flag_of_Zambia.svg.png',
      'Замбия',
      752614,
      15473905),
  countries(
      16,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/128px-Flag_of_Zimbabwe.svg.png',
      'Зимбабве',
      390757,
      15602751),
  countries(
      17,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/128px-Flag_of_Cape_Verde.svg.png',
      'Кабо-Верде',
      4033,
      520502),
  countries(
      18,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/128px-Flag_of_Cameroon.svg.png',
      'Камерун',
      475442,
      23344179),
  countries(
      19,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Flag_of_the_Canary_Islands.svg/128px-Flag_of_the_Canary_Islands.svg.png',
      'Канарские острова',
      7447,
      1995833),
  countries(
      20,
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/128px-Flag_of_Kenya.svg.png',
      'Кения',
      580367,
      46050302)
];
